stages:
  - build
  - test

variables:
  APP_NAME: "simple-java-web-app"

# Стадия сборки для ветки develop
build_develop:
  stage: build
  # Образ, в котором есть Docker CLI
  image: docker:stable
  script:
    - export DOCKER_IMAGE="lehater/${APP_NAME}:staging"
    # Логин в Docker Hub
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    # Сборка образа с локальным тегом
    - docker build -t $DOCKER_IMAGE .
    # Пуш образа в Docker Hub
    - docker push $DOCKER_IMAGE
  only:
    - develop


# Стадия сборки для ветки main
build_main:
  stage: build
  # Образ, в котором есть Docker CLI
  image: docker:stable
  script:
    - export DOCKER_IMAGE="lehater/${APP_NAME}:production"
    # Логин в Docker Hub
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    # Сборка образа с локальным тегом
    - docker build -t $DOCKER_IMAGE .
    # Пуш образа в Docker Hub
    - docker push $DOCKER_IMAGE
  only:
    - main

# Стадия тестирования для всех веток
test:
  stage: test
  #  image: eclipse-temurin:17
  script:
    - echo "=== Запуск тестов для приложения ==="
    - echo "=== Тесты пропущены т.к. в задании важен CI/CD пайплайн ==="
    - echo "=== Строчка для коммита в develop ветку ==="
  only:
    - develop
    - main
