stages:
  - build
  - test
  - deploy_staging
  - deploy_production

variables:
  DOCKER_TAG: >
    $([[ "${CI_COMMIT_REF_NAME}" == "master" ]] && echo "latest" || echo "${CI_COMMIT_REF_SLUG}")
  DOCKER_IMAGE: "${CI_REGISTRY_IMAGE}:${DOCKER_TAG}"

before_script:
  - git config --global user.email "ci@example.com"
  - git config --global user.name "CI/CD"

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "=== Сборка Docker-образа: $DOCKER_IMAGE ==="
    - docker build -t "$DOCKER_IMAGE" .
    - echo "=== Вход в Docker Registry ==="
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - echo "=== Пуш Docker-образа: $DOCKER_IMAGE ==="
    - docker push "$DOCKER_IMAGE"
  only:
    - develop
    - master

test:
  stage: test
  image: eclipse-temurin:17
  script:
    - echo "=== Запуск заглушки тестов для Java 17 приложения ==="
    - echo "Выполнение тестов..."
    - echo "Тесты пройдены (заглушка)!"
  only:
    - develop
    - master

deploy_staging:
  stage: deploy_staging
  image: alpine/git
  only:
    - develop
  script:
    - echo "=== Обновление манифестов для staging с использованием образа $DOCKER_IMAGE ==="
    - 'sed -i "s|image: .*|image: $DOCKER_IMAGE|" k8s/staging/deployment.yaml'
    - git add k8s/staging/deployment.yaml
    - git commit -m "Update staging image to $DOCKER_TAG for develop [skip ci]"
    - git push origin HEAD:develop
  environment:
    name: staging
    url: "http://example-staging-url"

deploy_production:
  stage: deploy_production
  image: alpine/git
  only:
    - master
  script:
    - echo "=== Обновление манифестов для production с использованием образа $DOCKER_IMAGE ==="
    - 'sed -i "s|image: .*|image: $DOCKER_IMAGE|" k8s/production/deployment.yaml'
    - git add k8s/production/deployment.yaml
    - git commit -m "Update production image to $DOCKER_TAG for master [skip ci]"
    - git push origin HEAD:master
  environment:
    name: production
    url: "http://example-production-url"
