stages:
  - build
  - test
  - deploy_staging
  - deploy_production

# Стадия сборки для ветки master
build_main:
  stage: build
  image: docker:stable
  services:
    - name: docker:dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  script:
    - docker info
    - export DOCKER_TAG="production"
    - export DOCKER_IMAGE="my-app:${DOCKER_TAG}"
    - echo "=== Сборка Docker-образа ==="
    - docker build -t "$DOCKER_IMAGE" .
    - echo "=== Вход в Docker Registry ==="
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - echo "=== Пуш Docker-образа ==="
    - docker push "$DOCKER_IMAGE"
  only:
    - main

# Стадия тестирования для всех веток
test:
  stage: test
  #  image: eclipse-temurin:17
  script:
    - echo "=== Запуск тестов для Java 17 приложения ==="
  only:
    - develop
    - main1

## Стадия деплоя в staging для ветки develop
#deploy_staging:
#  stage: deploy_staging
#  image: alpine/git
#  script:
#    - git config --global user.email "ci@example.com"
#    - git config --global user.name "CI/CD"
#    - echo "=== Обновление манифестов для staging с использованием образа ==="
#    - 'sed -i "s|image: .*|image: $DOCKER_IMAGE|" k8s/staging/deployment.yml'
#    - git add k8s/staging/deployment.yaml
#    - git commit -m "Update staging image to $DOCKER_TAG for develop [skip ci]"
#    - git push origin HEAD:develop
#  environment:
#    name: staging
##    url: "http://example-staging-url"
#  only:
#    - develop

# Стадия деплоя в production для ветки master
#deploy_production:
#  stage: deploy_production
##  image: alpine/git
##  variables:
##    DOCKER_TAG: "develop"
#  script:
#    - apk add --no-cache git
#    - git config --global user.email "ci@example.com"
#    - git config --global user.name "CI/CD"
#    - echo "=== Обновление манифестов для production с использованием образа ==="
#    - 'sed -i "s|image: .*|image: $DOCKER_IMAGE|" k8s/production/deployment.yml'
#    - git add k8s/production/deployment.yaml
#    - git commit -m "Update production image to $DOCKER_TAG for master [skip ci]"
#    - git push origin HEAD:master
#  environment:
#    name: production
##    url: "http://example-production-url"
#  only:
#    - main

#deploy_production:
#  stage: deploy_production
#  image:
#    name: bitnami/kubectl:latest
#    entrypoint: [""]
#  variables:
#    KUBECONFIG: "/root/.kube/config"
#  script:
#    - mkdir -p /root/.kube
#    - echo "$KUBECONFIG_FILE" > /root/.kube/config
#    - echo "Deploy to Production..."
#    - kubectl apply -f k8s/production
#  environment:
#    name: production
#  only:
#    - main