version: '3.8'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: gitlab.local
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.local'
        gitlab_rails['lfs_enabled'] = true
        gitlab_rails['registry_enabled'] = true
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    depends_on:
      - gitlab
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab_runner_config:/etc/gitlab-runner
    environment:
      - REGISTRATION_TOKEN=<your_registration_token>
      - CI_SERVER_URL=http://gitlab.local

#  minikube:
#    image: gcr.io/k8s-minikube/kicbase:v0.0.35
#    container_name: minikube
#    privileged: true
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - ~/.kube:/root/.kube
#      - ~/.minikube:/root/.minikube
#    environment:
#      - MINIKUBE_IN_STYLE=false
#    command: ["sleep", "infinity"]

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  gitlab_runner_config:
