apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-staging
  labels:
    app: myapp
    environment: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      environment: staging
  template:
    metadata:
      labels:
        app: myapp
        environment: staging
    spec:
      containers:
        - name: myapp
          image: registry.gitlab.local:5050/myapp:staging
          ports:
            - containerPort: 80
