apiVersion: v1
kind: Service
metadata:
  name: myapp-staging
  labels:
    app: myapp
    environment: staging
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: myapp
    environment: staging
