ci_access:
  projects:
    - id: "root/gitlab-kb8-cicd-example"
observability:
  logging:
    level: info
gitops:
  manifest_projects:
    - id: "root/gitlab-kb8-cicd-example"   # или <числовой ID проекта>
      paths:
        - path: "k8s/"             # папка с манифестами в репозитории
      deploy_agent:
        kubectl:
        # Доп. настройки kubectl apply