apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-staging
  labels:
    app: my-app
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: $DOCKER_USERNAME/my-app:staging
          ports:
            - containerPort: 80
