apiVersion: v1
kind: Service
metadata:
  name: my-app-staging-service
  labels:
    app: my-app
    environment: staging
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
