apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-production
  labels:
    app: my-app
    environment: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
#          image: 192.168.88.82:5050/root/my-app:production
          image: lehater/simple-java-web-app:production
          ports:
            - containerPort: 80
#      imagePullSecrets:
#        - name: regcred