apiVersion: v1
kind: Service
metadata:
  name: my-app-production-service
  labels:
    app: my-app
    environment: production
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001
  type: NodePort
