apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: my-app-repo
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@192.168.88.82/root/gitlab-kb8-cicd-example.git
  ref:
    branch: main
  secretRef:
    name: flux-system-ssh-key