apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-production
  labels:
    app: my-app
    environment: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: $DOCKER_USERNAME/my-app:production
          ports:
            - containerPort: 80
